

```{r}
a <- c(1,2,3)
b <- seq(0,1,length=10)
c <- 7:10
d <- seq(0,1,by=0.2)
e <- matrix(seq(1,12),nrow=2, ncol=6)
f <- matrix(seq(1,12),2,6)
g <- matrix(seq(1,12),2,6,byrow = TRUE)
sqrt(g)
g^2
dim(g)
```

```{r}
#indexing matrix
h <- matrix(1:16, 4, 4)
h
h[2,4]
h[c(1,2), c(3,4)]
h[2:3, 2:3]
h[1:2,]

```

```{r}
#negative index
h[-2,]
h[-c(1,3), -c(1,3,4)]
```

```{r}
# 1. Create a vector u that has values -10, -9, -8, . . . ,0. 
u <- c(-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0)
u <- seq(-10,0)
u <- -10:0
u
```

```{r}
# 2. Create another vector v that has values -0.1, 0.4, 0.9, 1.4, ., and there are 11 numbers (aka terms) in v. 

v <- seq(from = -0.1, by = 0.5, length.out = 11)
v
#Calculate the vector of u+v and u*v.
u+v
u*v
#4. Increase all terms in u by 1, and then take away 20% from all terms in v.
u+1
v*0.8
#Create a vector w that contains all the numbers from u and then v. Report the length of w.
w <- c(u,v)
w
length(w)
#6. Use a command to return the 14th, 15th and 16th value of w. What about the 2nd, the 5th, 9th and 21st value of w? What is the 23rd value?
w[c(14,15,16)]
w[14:16]
#7. Sort w in the descending order.
sort(w, decreasing = T)

```

```{r}
#Create the following matrix and assign it to the variable b_matrix. Extract a sub-matrix from b_matrix named subB.
##    a  b  c  d  e 
## A  1  3  5  7  9 
## B 11 13 15 17 19 
## C 21 23 25 27 29 
## D 31 33 35 37 39

b_matrix <- matrix( seq(1,39,by=2),4,5,byrow=T, dimnames = list(
c("A", "B", "C", "D"),
c("a", "b", "c", "d", "e") ))
b_matrix
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```